### ISSUE TITLE
error: declaration does not declare anything [-fpermissive]

### ISSUE THREAD

**Issue by TonyginSLC** [jack-ullery/libappanvil#9]
Trying to run Make on libappanvil. I get the following:

Consolidate compiler generated dependencies of target autogenerated_sources
[ 14%] Built target autogenerated_sources
Consolidate compiler generated dependencies of target appanvil-dev
[ 14%] Building CXX object CMakeFiles/appanvil-dev.dir/src/apparmor_parser.cc.o
In file included from /home/anthony/Downloads/libappanvil-main/src/parser/driver.hh:4,
                 from /home/anthony/Downloads/libappanvil-main/src/apparmor_parser.cc:2:
/home/anthony/Downloads/libappanvil-main/src/parser/parser.h:224:39: error: declaration does not declare anything [-fpermissive]
  224 | #define unused __attribute__ ((unused))
      |                                       ^
make[2]: *** [CMakeFiles/appanvil-dev.dir/build.make:258: CMakeFiles/appanvil-dev.dir/src/apparmor_parser.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:209: CMakeFiles/appanvil-dev.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

Any suggestions?

**Comment by jack-ullery** [comment]
Thank you for reporting this.

This error seems to be thrown by g++ (and not clang). For now, a workaround could be switching compilers.

It seems the offending code was leftover from [apparmor_parser](https://gitlab.com/apparmor/apparmor/-/tree/master/parser) which this repository is adapted from. I'll take a look at fixing this soon

**Comment by TonyginSLC** [comment]
Thanks. Appreciate the reply.

--Tony
________________________________
